spring.application.name=ordem-servico
# Conexão com o Docker (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/db_os
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create

# Logs para ver o SQL no terminal do Mac
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true